# Generated by Django 5.0.2 on 2024-03-01 13:26

import bahis_management.taxonomies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativeRegionLevel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="The region level identifier, e.g. 1 for state, 2 for district, etc.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title for the administrative region level, e.g. District", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="The human-readable title for the taxonomy, e.g. Disease List", max_length=150
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The machine-readable name for the taxonomy, e.g. disease-list", unique=True
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        help_text="The CSV file containing the taxonomy data, taxonomies should meet the XLSForm Choices specification",
                        upload_to="taxonomies",
                        validators=[bahis_management.taxonomies.models.validate_file_is_csv],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdministrativeRegion",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        help_text="The heirarchical identifier for the administrative region level, e.g. a level 1 geography may have an id of 01, and a level 2 geography may have an id of 01001",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="The name of the region", max_length=150)),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_administrative_region",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent region of this region (leave blank for top level regions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomies.administrativeregion",
                    ),
                ),
                (
                    "administrative_region_level",
                    models.ForeignKey(
                        help_text="The region administrative level",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomies.administrativeregionlevel",
                    ),
                ),
            ],
        ),
    ]
