# Generated by Django 5.0.2 on 2024-03-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModuleType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="The type of module as understood by the BAHIS-desk app", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the workflow, this will be rendered as a button in the BAHIS-desk app",
                        max_length=150,
                    ),
                ),
                ("source_form", models.TextField(blank=True, help_text="The source form for this workflow", null=True)),
                (
                    "destination_form",
                    models.TextField(blank=True, help_text="The destination form for this workflow", null=True),
                ),
                (
                    "definition",
                    models.JSONField(
                        help_text="A JSON object mapping fields from the list definition's form to fields in the destination form definition"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this workflow is active in the BAHIS-desk app"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the module, this will be rendered in the BAHIS-desk app", max_length=150
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="The icon to be used from the MUI icons set (https://mui.com/material-ui/material-icons)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description of the module, this will be rendered in the BAHIS-desk app",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.TextField(
                        blank=True, help_text="The form to be used for this module (if type is form or list)", null=True
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="The external URL to be used for this module (if type is external URL)",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The sort order for this module in the BAHIS-desk app (smaller means higher)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this module is active in the BAHIS-desk app"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_module",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent module for this module if part of a heiarchy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="desk.module",
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(
                        help_text="The module type as understood by the BAHIS-desk app",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desk.moduletype",
                    ),
                ),
            ],
        ),
    ]
